### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MaxBald** [gileli121/WindowTop#1]
Using WindowTop portable (OS Win7 x64), when you shrink a "set on top" window and then unshrink it, the window doesn't remain on top and you have to press ALT+z twice to restore it.

**Comment by gileli121** [comment]
Thank you for there report!
I confirm the bug and I will fix it on next version

**Comment by gileli121** [comment]
I fixed the issue now and I hope to release it soon

**Comment by gileli121** [comment]
Fixed again (it did not fixed right in the previous version)
