### ISSUE TITLE
Shrink feature - Implement option to auto move the shrink-boxes when they covering images/texts

### ISSUE THREAD

**Issue by gileli121** [gileli121/WindowTop#108]
The idea is to add an option in the Shrink feature that the shrink-box will automatically move to an area where there is no text/image (if such area available)

We will use the developments of #103
The way the shrink-box will move will be like the implementation of #103 
Example video: https://www.youtube.com/watch?v=MYUJ7J1IqEs

**Comment by gileli121** [comment]
First preview of this improvment
https://www.youtube.com/watch?v=ef07NnUKxjs

**Comment by gileli121** [comment]
Implemented.
Check this build:
[Build.zip](https://github.com/gileli121/WindowTop/files/6643293/Build.zip)

Enable this option:
![image](https://user-images.githubusercontent.com/17680514/121795796-b3a4ba80-cc1c-11eb-85f6-a089807e3987.png)

**Comment by jakkaas** [comment]
I am sorry but the shrink feature in this build is not working for me. there is an command prompt window always opened while using this build. I am not sure any file missing or not functioning because of this but currently I am not able to use the new feature.

**Comment by gileli121** [comment]
@jakkaas 
Please make sure to delete the `settings.json` file and try again.
I made some changes that may cause the program to crash in case you have the old `settings.json` file that generated from the older beta build.

About the black window, ignore it.. this is because it is a beta build.
You will not get the black window in the final build

**Comment by jakkaas** [comment]
The function is not working for me. I tried deleting the setting but again the settings get reverted to default.

**Comment by gileli121** [comment]
@jakkaas 
Did you enabled this option?
![image](https://user-images.githubusercontent.com/17680514/121816615-4aa55d00-cc85-11eb-8ca7-43c251c947f1.png)

**Comment by jakkaas** [comment]
yes. I enabled it. I tried deleting the setting and then again enabling it. But still no luck.

These are the file in the build
![image](https://user-images.githubusercontent.com/43289832/121816895-ee9a0300-cc9b-11eb-9530-52cf7a680ca2.png)

**Comment by gileli121** [comment]
@jakkaas 
Please try this build:
[Build 14.6.21.zip](https://github.com/gileli121/WindowTop/files/6644649/Build.14.6.21.zip)

Maybe now it fixed somehow
In addition, in this build I added option to enable the auto move specific for one shrink window
![image](https://user-images.githubusercontent.com/17680514/121821918-c793ff00-cca4-11eb-8299-2a1f305ad510.png)

Let me know if it works

**Comment by gileli121** [comment]
@jakkaas 
Try the last build from 
https://github.com/gileli121/WindowTop/issues/103#issuecomment-860403870

**Comment by jakkaas** [comment]
But I don't know auto switching is still not working for me. I don't know whether an old install or any other program is causing this issue.

https://drive.google.com/file/d/130UnCdiuoioPU70AhasZVGBDrvCL0fF0/view?usp=sharing

**Comment by gileli121** [comment]
@jakkaas 
I can't access the file you shared in google drive.
Please give access.

> But I don't know auto switching is still not working for me.

Do you mean that the shrink not automatically moving to an area without text/image?

**Comment by jakkaas** [comment]
Please try to access now

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 15, 2021 at 2:14 AM, Gil ***@***.***> wrote:   


@jakkaas
I can't access the file you shared in google drive.
Please give access.


But I don't know auto switching is still not working for me.


Do you mean that the shrink not automatically moving to an area without text/image?

**Comment by gileli121** [comment]
@jakkaas 
Please try the new build from here:
https://github.com/gileli121/WindowTop/issues/103#issuecomment-861786608
Let me know if it fixed

**Comment by jakkaas** [comment]
yes, this is also fixed.

**Comment by gileli121** [comment]
I assume that the auto-move option in the Shrink feature is stable.
I will mark this task as done

**Comment by gileli121** [comment]
@jakkaas 
This video is result of 21 days of work
https://www.youtube.com/watch?v=ApxpPF8iR08


This is the final version of the feature. 
You can download from here: 
https://github.com/gileli121/WindowTop/releases/tag/v5.4.2
