### ISSUE TITLE
Feature Request: Option to keep Anchor Right/Left/Top/Bottom of Screen

### ISSUE THREAD

**Issue by jakkaas** [gileli121/WindowTop#116]
The anchor feature is great and I am using it daily.
But for a person like me who doesn't like much movement around the screen (OCD I guess) and like to keep my window screen organized I don't like the auto movement of anchor. It too much of a distraction for me. So I use manual dragging the anchor option. But the issue with this is that whenever I open any new window, popup, or tab (group user) the new window opens in the center of the screen (I work with different windows continuously). 

I would like to have an option of open & keeping the anchor to one part of the screen  (Right/Left/Top/Bottom) automatically after any windows/tab/popup opens.

Thanks

**Comment by gileli121** [comment]
I see your point.. 
You don't like that the anchors showing on the center (when auto-move disabled) and you want to change it right?

**Comment by jakkaas** [comment]
For me right. Someone else might want on other side. Thanks

**Comment by gileli121** [comment]
@jakkaas 
I think that your problem here is that they showing above the text when they first created.
I think that instead of making it showing on left/right sides, a better option is that when it first created will will not created above text.

This is what I will implement now and give you to test.
Then you will let me know if this is better behavior or not

**Comment by gileli121** [comment]
On second thought, I think that you are right.
Your requested behavior looks better on second thought

**Comment by jakkaas** [comment]
The issue is it not only shows above the text but also in the middle of the screen which is something distracting from actual work and even more distracting when you open multiple windows continuously and then every time you have to move to the side to avoid distraction. Many people like me who have an OCD of organizing will find it super distracting to find something in between and then have the urge to move it to the side while working
I find this type of side anchors quite mentally peaceful: )

![image](https://user-images.githubusercontent.com/43289832/124265374-37cecb80-db53-11eb-9c3d-b549dbd2bc72.png)

**Comment by jakkaas** [comment]
For those who are fine with anchors in middle for them, auto movement is a great option

**Comment by gileli121** [comment]
@jakkaas 
Please try this build:
[Build 2.7.21-1.zip](https://github.com/gileli121/WindowTop/files/6754739/Build.2.7.21-1.zip)

You have there new option:
![image](https://user-images.githubusercontent.com/17680514/124278861-795d7780-db4f-11eb-8cd0-1a9ce1a6a513.png)


Let me know how it works for you

**Comment by jakkaas** [comment]
Working great. Thank you so much

**Comment by gileli121** [comment]
@jakkaas 
Please try this build:
[Build 2.7.21-2.zip](https://github.com/gileli121/WindowTop/files/6755710/Build.2.7.21-2.zip)

I fixed some other bug (not related to this request but it still can break it)
Please let me know how it works for you.

Thanks

**Comment by jakkaas** [comment]
> @jakkaas
> Please try this build:
> [Build 2.7.21-2.zip](https://github.com/gileli121/WindowTop/files/6755710/Build.2.7.21-2.zip)
> 
> I fixed some other bug (not related to this request but it still can break it)
> Please let me know how it works for you.
> 
> Thanks

It is still working for me thanks.

**Comment by gileli121** [comment]
@jakkaas 
Great!
Closing this task
