### ISSUE TITLE
How to restore window configuration?

### ISSUE THREAD

**Issue by koboltzz** [gileli121/WindowTop#18]
Hi, I really like this powerful tool and bought the pro edition. I wonder where 'restore window configuration' is stored since I can 'save window configuration'?

**Comment by gileli121** [comment]
Hello, why do you need to restore?
The settings it saves are very simple - it just saves if to set on top/dark/opacity automatically for the program you wanted.

If for example, you saved configurations that it will automatically set the program windows on top then what you can do is disable to the "Set Top" option (that automatically enabled) and then resave the window configuration.

In simple words - just resave the window configurations while the set-top or whatever it is is disabled


Hope it helps.

**Comment by koboltzz** [comment]
Thx for your answer :)
but I don't understand it... 
I thought that if I configure windowtop for a program/window and click on 'save window configuration', the next time I start this program my settings will be automatically reactivated. Or, if that doesn't work, that I could click on 'restore configuration' and all parameters would be as I had them (only for this program).
But somehow nothing happens, no matter if I save or not, the settings are always default, so everything is disabled. What is that feature all about ?

**Comment by gileli121** [comment]
`I thought that if I configure windowtop for a program/window and click on 'save window configuration', the next time I start this program my settings will be automatically reactivated`
You are right and it should work and for me it does work.
If it is not working for you, it is an issue.  

What version are you using and on which program you try the option?

**Comment by koboltzz** [comment]
Thx a lot for your support :)

Program: IP Camera Viewer 4.09 (freeware which you can download everywhere)
Tool: WindowTop 3.4.5
OS: Windows 10, 2004 Update
Issue: Saving opacity and/or click through and/or shrink size doesn't get applied after closing and opening program again.

**Comment by gileli121** [comment]
Sorry for the late reply.
I was busy recently.

Did you save window configuration while the "Shrink" mode enabled and you expect that the "Shrink" mode will automatically be enabled each time you open the window?

**Comment by koboltzz** [comment]
No problem. 
For example yes, but also everything else like stay on top or click through won't get saved.

**Comment by gileli121** [comment]
It does not save the Shrink. it will not auto-enable it even if you did "Save window configuration"
I think that this is wrong behavior and it should also enable the Shrink mode automatically.
For other functions, such as Set-Top it will and should enable it automatically.

But sound that nothing in the "Save window configuration" works.

If you try it on other windows from other software, it works?
Did you installed WindowTop or use the portable version?
If you did install it, did you changed the default installation location?

There is a known issue that if you change the default install location, some functions will not work.
But it is new that "Save window configuration" fail to work and it never reported before

**Comment by koboltzz** [comment]
> If you try it on other windows from other software, it works?
Sadly it doesn't work.
> Did you installed WindowTop or use the portable version?
I use the portable version on an encfs encrypted virtual drive where no windows permissions (acl) are usable. Maybe that's confusing your nice tool. But other tools like portable notepad++ work perfectly.
Maybe you want to use appdata/local or appdata/roaming for storing essential files and settings even when using your portable build (like many windows programs do), so it will always work ?

**Comment by gileli121** [comment]
Maybe the software fails to store or update the `WindowTop.settings` file.
WindowTop.settings is a file that located when WindowTop.exe is located (if you use the portable version)

Please open the file with notepad and check if anything there is updated after you change the settings or in your case - save window configuration.

**Comment by koboltzz** [comment]
Yep, it updates the file, but it contains only ArrowXPos, darkmode and settop entries. No wonder why from my point of view nothing (click through and/or shrink size) is saved and restored. And even if settop is set to '1' ipcamviewer launches with settop off.

**Comment by gileli121** [comment]
Can you try to install the program and see if the issue still happens?

**Comment by koboltzz** [comment]
This would contradict the intended purpose. You didn't ask, but the purpose of the encfs virtual drive is that it is synchronized to all my pcs and laptops via a cloud provider, so I have all my current programs on every computer at all times.
Therefore I am mostly dependent on portable programs. I can live with it, to adjust the three settings I need every time :)

**Comment by gileli121** [comment]
And when it synchronized, `WindowTop.settings` is updated as well on these computers with the changes you made?

Sorry that I can't help yet.
Looks like it is related to the configuration you have.

I asked to see how it works as installed to be sure that it is something to do with the portable version.
If you can't install it then fine.

**Comment by koboltzz** [comment]
Yes, the file is updated. I know why you asked this, but since you're probably testing the tool on Windows 10 yourself and it works, it's probably because the portable version doesn't handle the missing ACLs.

**Comment by gileli121** [comment]
@koboltzz 
In v5 you have "Delete window configuration"
![image](https://user-images.githubusercontent.com/17680514/113940778-adeabd00-9806-11eb-956b-6a387c668e87.png)

Is this what you wanted?
Can I close this request?

**Comment by gileli121** [comment]
No response from user.
Assumed that the request handled. 
Issue closed
