### ISSUE TITLE
[Request] Ability to toggle off toolbar for certain programs

### ISSUE THREAD

**Issue by grravity** [gileli121/WindowTop#2]
Requesting the ability to blacklist certain programs. It's annoying for games to have the bar at the top when you hover over that area.

**Comment by gileli121** [comment]
Thanks for the idea.
I agree that it is important feature and I will try to add it on the next big updates

**Comment by 10101000** [comment]
I'd also like to see this feature implemented. I'd suggest both a whitelist and blacklist. Additionally, the ability to blacklist all full screen applications would be very helpful. Perhaps sub options to distinguish between exclusive full screen and windowed borderless would be useful. Thanks!

**Comment by gileli121** [comment]
Thanks for your feedback.
I will implement the feature now.
It will be available in the next versions.

**Comment by gileli121** [comment]
Hello Again, I implemented the feature.

Here is how it looks:
![image](https://user-images.githubusercontent.com/17680514/79173636-dd880480-7e00-11ea-91c9-7c840b5ea621.png)

![image](https://user-images.githubusercontent.com/17680514/79173701-07412b80-7e01-11ea-9b18-2693acc3a580.png)


I attached an experimental version with this feature.
Please try it and let me know about any feedback you have:

[WindowTop_github_request2.zip](https://github.com/gileli121/WindowTop/files/4472515/WindowTop_github_request2.zip)

**Comment by 10101000** [comment]
Thanks! The experimental version is working perfectly.
