### ISSUE TITLE
WindowTop dark mode appears to cause mouse grab in VMWare guest.

### ISSUE THREAD

**Issue by zelch** [gileli121/WindowTop#25]
So, on one of my systems I have Windows running as a VMWare guest.

When WindowTop is not running, or is running but no windows are using it, everything behaves as expected.  Most specifically, my mouse cursor moves freely in and out of the guest window.

When I have WindowTop mark a window as dark, this behavior changes drastically.  Windows grabs the mouse cursor and I have to use the hot keys to grab/ungrab when switching between guest and host windows.

At a guess, VMWare thinks that a game is running on the guest and is wanting more 'raw' mouse inputs instead of absolute positioning cursor inputs.

Update: Yep, it's the 'optimize mouse for games' in auto mode in VMWare which is triggering.  If I set it to 'Never' the problem goes away, though that makes things more awkward if I also have situations where I want that behavior.

**Comment by gileli121** [comment]
Hello,
Sorry for the late reply.
Can you share please some video that shows the issue and send it to my email?
Unfortunately, I did not understand.
