### ISSUE TITLE
CPU usage a little higher

### ISSUE THREAD

**Issue by tuchit** [gileli121/WindowTop#26]

**Comment by gileli121** [comment]
Hello,

What version do you use?
In v3.3.7 there was a fix about CPU and RAM usage 
![image](https://user-images.githubusercontent.com/17680514/85788457-ace41580-b735-11ea-8d50-8b08775fcb8a.png)

And the fix should be also on newer versions.

How much CPU does it use?

What is your hardware specification?

Is this happens when you use some specific function (such as transparency, set dark, shrink)? 
If so, what is the function?

**Comment by tuchit** [comment]
cpu usage at 1.6-3.0
i5
im using 3.4.5

> Is this happens when you use some specific function (such as transparency, set dark, shrink)?
No, I just started it and didn't use it at all

**Comment by gileli121** [comment]
In my case, it is 0-2% CPU usage using I7 CPU.
It was worse before v3.3.7 

Unfortunately, there is nothing more I can do to improve it more.
I already tried to solve the issue as much as I can.

This issue will be solved better when I will redevelop the software in C# and it will not happen soon
But I consider doing this.

**Comment by gileli121** [comment]
If you don't use this:
![image](https://user-images.githubusercontent.com/17680514/85924531-a1126380-b89b-11ea-8f01-f38a70d8801e.png)

You can disable it and only use hot keys.
This is what makes part of the CPU usage.

 Just disable it from here 
![image](https://user-images.githubusercontent.com/17680514/85924542-bbe4d800-b89b-11ea-8700-a732d9dda1d3.png)

To configure hotkeys, do it from here:
![image](https://user-images.githubusercontent.com/17680514/85924560-d8811000-b89b-11ea-925f-b903e2e608ae.png)

It is a workaround if you don't want the toolbar.
Let me know if it helps

**Comment by tuchit** [comment]
> You can disable it and only use hot keys.
no, it doesn't work. cpu usage is still high.

**Comment by gileli121** [comment]
Thanks for the report.

I will keep the issue open and I want to see if more users complain about it.
If it has more users with this problem and the CPU usage is high, I will prioritize the issue higher.

**Comment by gileli121** [comment]
@tuchit 
I rewrote the whole program in C# instead of Autoit.
You can download it from here:
https://github.com/gileli121/WindowTop/releases/tag/v5.x.x

Let me know if use less CPU

**Comment by tuchit** [comment]
@gileli121
Awesome, CPU usage is normal in the version 5.0
Nice work!
