### ISSUE TITLE
[Request] Black and white

### ISSUE THREAD

**Issue by Wolfrisger** [gileli121/WindowTop#3]
Hello,
Is it possible to make everything black and white(grayscale) in the dark mode?

Thanks.

**Comment by gileli121** [comment]
Yes, but why do you need such an option?

**Comment by Wolfrisger** [comment]
> Yes, It is possible to develop. but why do you need such an option?

well, I actually ask this for a total color blind guy, he can't recognize many colors but if they are in gray-scale he can then recognize them with the brightness level.

**Comment by gileli121** [comment]
I can develop a small program/script that does this for the whole screen.
I see that this is what you actually need in your case.

Let me know if you interested
