### ISSUE TITLE
RDP session windows set on top by default

### ISSUE THREAD

**Issue by demdante** [gileli121/WindowTop#33]
Hello.  I have noticed an issues with Windowtop where RDP windows are configured with "set top" property as enabled by default.  This is not the default behavior of RDP session windows: the "set top" property should not be enabled by default.

**Comment by gileli121** [comment]
Thanks for the report.
What program do you use for RDP session?

**Comment by demdante** [comment]
> 
> 
> Thanks for the report.
> What program do you use for RDP session?

@gileli121 ...  The built in Windows "Remote Desktop Connection,"  Give me a little time and I will record my screen demonstrating the behavior.

**Comment by demdante** [comment]
@gileli121 Here is that screen recording that I promised:

![windowtop](https://user-images.githubusercontent.com/64720591/87272693-90323680-c4c6-11ea-88f5-799aeb3cf0b9.gif)

**Comment by gileli121** [comment]
I understand.
Strange.
Thanks for the report, I will check it next week.

**Comment by gileli121** [comment]
The fix for #34 did not fix this issue.
So it is not the same as #34

**Comment by gileli121** [comment]
I was wrong. The fix for #34 fixed also this issue.

**Comment by gileli121** [comment]
Released
