### ISSUE TITLE
Applications which allow the Window.Topmost property to be configured internally make Windowtop behave strangely

### ISSUE THREAD

**Issue by demdante** [gileli121/WindowTop#34]
Hello.  This is similar to the issue that I previously posted, but slightly different.  I have noticed that WindowTop behaves strangely or causes an application to behave strangely when said application allows the Window.Topmost property to be configured internally within the application.  An example of this that I most recently ran into was with the application "Media Player Classic", which is included in the [K-Lite Codec Pack](https://www.codecguide.com/download_kl.htm). As you can see, Media Player Classic allows me to configure the Window.Top property as a setting within the application:

![image](https://user-images.githubusercontent.com/64720591/87269139-cfa75580-c4bb-11ea-8fbf-773d404244ee.png)

So, as you can see, the application is currently configured to always be displayed on top or other windows, and windowtop does reflect this.  However, lets take a look and see what happens when I use media player classic's internal settings to set the application window back to its default behavior (aka with Window.topmost property set to false):

![windowtop](https://user-images.githubusercontent.com/64720591/87271614-47c54980-c4c3-11ea-9b0e-eac7da2c91f0.gif)

As you can see, even if I configure the application so that the window.topmost property is set to false, the Windowtop application is still forcing the application to display on top.  The Media player classic application only starts behaving as expected once I exit the windowtop application.  Strangely, once I have set media player classic to no longer display on top within the internal settings, I then tried to close and then re-open the application, to see if Windowtop would correctly read that the media player classic should no longer be displayed on top.  Oddly enough, even though media player classic's default configuration is to not display the window on top, the WindowTop application is still forcing the media player classic window to do so be default when launched:

![windowtop](https://user-images.githubusercontent.com/64720591/87272265-37ae6980-c4c5-11ea-9a92-cebb6c1ab496.gif)

So, as you can see, windowtop doesn't seem to play nice with applications which can internally configure its window.topmost property..

**Comment by gileli121** [comment]
Great bug description!
I understand. I think that it is the same issue as #34 
I will check it next week.

**Comment by gileli121** [comment]
Fixed in v3.4.7

**Comment by gileli121** [comment]
@demdante 
Please try this version.
[WindowTop v3.4.7-test.zip](https://github.com/gileli121/WindowTop/files/4980063/WindowTop.v3.4.7-test.zip)

Extract it and replace the file `WindowTop.exe` with the file inside the zip file.
Let me know how it works for you

**Comment by gileli121** [comment]
Released
