### ISSUE TITLE
Auto hide taskbar not popping up

### ISSUE THREAD

**Issue by Sylvaerin** [gileli121/WindowTop#345]
Hey, 
I've just started using windowtop, but one thing is really bugging me: while windowtop is opened, the auto hide taskbar simply won't pop up if I hover my mouse on the bottom of my screen while I have a maximized window opened. The problem seems to be that the taskbar shows up behind other windows, as even a non-maximized one will stay on top of it.
The solution is to press the window key, which still works, but far too annoying for me to continue using windowtop.
I hope I'm missing a setting to fix this.

**Comment by gileli121** [comment]
@Sylvaerin 
What is your OS (Windows 10, 11, etc)?
Do you only need to run WindowsTop to get the problem, or does it happen after using some feature?

**Comment by Sylvaerin** [comment]
I'm on windows 10. Simply having windowtop opened causes the issue, closing it instantly fixes it.

**Comment by gileli121** [comment]
@Sylvaerin 
I was able to reproduce the same issue also on Windows 11.
I am checking it.

Thanks for the report.

**Comment by gileli121** [comment]
Investigation about what code causes the issue is done.
Now, I am proceeding to fix it.

**Comment by gileli121** [comment]
@Sylvaerin 
Please try this version
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.7

I fixed it

Let me know if it works properly now

**Comment by Sylvaerin** [comment]
It's working, thanks for the help!

**Comment by gileli121** [comment]
Glad to help!
This was an important bug that was there from the beginning.
It is good that it is finally fixed.
