### ISSUE TITLE
WSLtty 'forgets' opacity setting on focus

### ISSUE THREAD

**Issue by daagar** [gileli121/WindowTop#35]
Attempting to use WindowTop's opacity feature with WSLtty (https://github.com/mintty/wsltty) works while setting the value with the slider. However, as soon as the dialog closes, the window reverts to default.

WSLtty provides its own transparency setting in the options, but even though the setting is 'Off' it appears to override WindowTop. The transparency option in WSLtty for 'high' is still fairly opaque which is why I was trying to use WindowTop, as it allows for a MUCH more transparent window.

Tested with both versions of WindowTop (though Windows version is 1909, so I understand using the 2004 version isn't necessarily a valid test).

**Comment by gileli121** [comment]
I was able to reproduce the issue

**Comment by gileli121** [comment]
Fixed

**Comment by daagar** [comment]
Much appreciated, thank you!

**Comment by gileli121** [comment]
Please try this version.
[WindowTop v3.4.7-test.zip](https://github.com/gileli121/WindowTop/files/4980063/WindowTop.v3.4.7-test.zip)

Extract it and replace the file `WindowTop.exe` with the file inside the zip file.
Let me know how it works for you

**Comment by gileli121** [comment]
btw, this file I sent you contains also new feature #15 
I would like to know how it works

**Comment by daagar** [comment]
Both the fix to this issue and the new feature seems to be working as expected!

**Comment by gileli121** [comment]
Released

**Comment by gileli121** [comment]
Unverified in v5
Reopened

**Comment by gileli121** [comment]
Fixed in v5 (not released yet)

**Comment by gileli121** [comment]
Released in v5.1.6
