### ISSUE TITLE
[Feature Request] Shortcuts to cycle transparency 

### ISSUE THREAD

**Issue by Vino4** [gileli121/WindowTop#352]
Hello friend :)

I often cycle between desktops and depending on what app I'm using behind my transparent/click-through window- I like to use different levels of transparency. Currently the only way to do this is to disable hover over the transparent/click-through window -> hover on opacity -> drag the transparency toggle bar.

It would be really awesome to have a configurable hotkey that cycles between different transparency profiles for all transparent windows.

For example, I'd set `win-key + /` to quickly cycle all current transparent windows between 90% and 50%.

That way when I need to read something under the transparent windows I can quickly toggle transparency down 50%, then toggle when I'm done back to 90%.

Thank you so much ^^

**Comment by gileli121** [comment]
Thanks for the idea.
It is a nice idea, and will work on it when I add more features

**Comment by gileli121** [comment]
First screenshots:
![image](https://github.com/user-attachments/assets/52475b9b-2cdb-4565-88aa-c19fbd478cbb)
![image](https://github.com/user-attachments/assets/d335eb24-93e7-4ab0-829e-8635d2261c37)
![image](https://github.com/user-attachments/assets/eee2b86c-57be-43b4-881d-e8e610547d41)

**Comment by gileli121** [comment]
Implemented

You can now configure a shortcut to quickly adjust opacity using the mouse scroll button!  
This setting can be configured under hotkey settings or opacity settings:  

![image](https://github.com/user-attachments/assets/20a94f20-f198-44da-9cb5-aeb6261412c1)

[opacity scroll hotkey.webm](https://github.com/user-attachments/assets/223835a5-ff03-4d7f-a520-1e7155047b1c)

**Comment by gileli121** [comment]
Currently, there is a known issue where it does not function on windows with higher privileges (elevated/admin windows) unless WindowTop is also running as Admin.

I have spent some time trying to find a workaround, but unfortunately, no solution has been found yet.
