### ISSUE TITLE
Rotate hue 180 degree in dark mode

### ISSUE THREAD

**Issue by luo-chuan** [gileli121/WindowTop#362]
Rotating hue 180 degree in dark mode will keep red in red, green in green, blue in blue.

**Comment by gileli121** [comment]
This sounds like extremely great suggestion and[ should not be hard addition](https://learn.microsoft.com/en-us/windows/win32/direct2d/hue-rotate)!
When I finish with https://github.com/WindowTop/WindowTop-App/issues/332 this is probably something that I will implement first.

**Comment by gileli121** [comment]
@luo-chuan 

It implemented

| Before                                                                                                    | After                                                                                                     |
|-----------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|
| ![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/4e0897a9-df56-4069-99fd-51635eadc022) | ![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/386981e1-e44d-420e-bbb7-a88c202050f5) |


Please try this version and let me know how it looks
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.10

I am wondering if this should be an option in settings, or it is just how it should work anyway (and it was a bug)
I am concerned that this proposed change might impact the readability of some texts.
Please give me feedback if after applying it, you can still easily read the text as before.

**Comment by luo-chuan** [comment]
With v5.22.10. Effects are as follows.
Before: 
![图片](https://github.com/WindowTop/WindowTop-App/assets/33930736/ac566bdf-77c0-4fed-8bad-9cd0605e5717)
After: 
![图片](https://github.com/WindowTop/WindowTop-App/assets/33930736/b58445ee-cd21-4f83-9469-738a21ee1180)
That is great.

**Comment by gileli121** [comment]
@luo-chuan 
looks great
But I think that it should be option in settings
Because in some cases the text is a little less readable

**Comment by gileli121** [comment]
@luo-chuan 
Please check this version
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.23.0

The difference now is that it added as an option that you can change from toolbar and settings

![dark mode fix colors](https://github.com/user-attachments/assets/369d4510-a7a5-463f-aaae-f03c1a1ec8a3)

![image](https://github.com/user-attachments/assets/293f32af-41eb-46fa-a470-d83a5b00b311)
