### ISSUE TITLE
Window disappears if opacity is disabled while click-through is enabled

### ISSUE THREAD

**Issue by samarthc** [gileli121/WindowTop#37]
Steps to reproduce:
Enable the "opacity" and enable click-through. "Set top" gets enabled automatically.
Turn off the "opacity" option. Window disappears but WindowTop menu is still visible.
Turn on "opacity" again. Window reappears with the previous transparency setting.
Now turning off "opacity" makes the window opaque again and disables click-through, as expected.

**Comment by gileli121** [comment]
Fixed

**Comment by gileli121** [comment]
@samarthc 
Please try this version.
[WindowTop v3.4.7-test.zip](https://github.com/gileli121/WindowTop/files/4980063/WindowTop.v3.4.7-test.zip)

Extract it and replace the file `WindowTop.exe` with the file inside the zip file.
Let me know how it works for you

**Comment by gileli121** [comment]
Released
