### ISSUE TITLE
WindowTop Error

### ISSUE THREAD

**Issue by ZenRevision** [gileli121/WindowTop#376]
So I get this error notification, everytime I close any window that WindowTop is applying either Glass or Transparency to (it doesn't happen with Dark).

The notice appear in the bottom right of the screen and reads:
> ### WindowTop Error
> Failed to disable transparency for the window

This is very annoying, as it's large orange overlay, and it always appears when closing any window with transparency (or glass) applied. I have several apps that I use frequently and have saved configs for, so they get transparency or glass applied automatically, and always trigger this error when their windows are closed.

Critically, there should be an option to disable error notifications. Also perhaps, WindowTop could discard transparency for windows which no longer exist, more elegantly, in such a way that doesn't trigger an error.

Thanks for all your great work!

**Comment by gileli121** [comment]
Thanks for the report!
I reproduced the bug.
I will work on a fix

**Comment by gileli121** [comment]
@ZenRevision 

I’ve fixed the issue! Please try downloading from the following links:  
- [Installer Version](https://github.com/WindowTop/WindowTop-App/releases/download/5.23/WindowTop.5.23.4.-.setup.exe)  
- [Portable Version](https://github.com/WindowTop/WindowTop-App/releases/download/5.23/WindowTop.v5.23.4.Portable.zip)  

I've also resolved a few other problems (more details can be found here: #383).

### Full Release Notes:
* Enhanced stability by addressing two common crash errors (errors 1 and 3 from [#383](https://github.com/WindowTop/WindowTop-App/issues/383)).
* Resolved the "Failed to disable transparency for the window" issue that occurred when closing the window with Glass mode enabled ([#376](https://github.com/WindowTop/WindowTop-App/issues/376)).

Please let me know how it works for you!
