### ISSUE TITLE
How to associated my license with my google email

### ISSUE THREAD

**Issue by AiraPaul** [gileli121/WindowTop#379]

**Comment by gileli121** [comment]
Hello, this feature is supported on new license keys.
Old license keys purchased before this development do not support association with email.

**Comment by gileli121** [comment]
When did you purchase the license key?

If the license key supports it, you should see this after you apply the license key:

![image](https://github.com/user-attachments/assets/87e5f7d6-0c94-4f22-bcd1-bfb37d8b7600)

Click on the "Associate with email". It will open page on the website where you can complete the operation.
