### ISSUE TITLE
Won't work on all programs

### ISSUE THREAD

**Issue by Rhaedas** [gileli121/WindowTop#45]
Works fine for any program I start normally, but it won't work on programs that are run by another program. Programs started by script (batch file) or by a macro program (Voice Attack) would not be affected by the WindowTop menu buttons at all (the menu was there on the windows), but all would work fine if I ran them via a shortcut or clicking on them in File Manager. Running Windows 10 (2004).

**Comment by gileli121** [comment]
@Rhaedas 
I tried to reproduce it without success.
I created `bat` file with content:
```bat
notepad
```
And then I started it.
A command-line window opened with a notepad window.
I was able to control enable/disable functions like set-top.

Please give more information like such as the programs I can reproduce it with.

Thanks

**Comment by gileli121** [comment]
Closed. It may fixed in v5 that rewritten in C#
