### ISSUE TITLE
Shrink Pro & Shrink problem in high refresh rate screen

### ISSUE THREAD

**Issue by sunny7bit** [gileli121/WindowTop#46]
My computer is Lenovo Y7000P 2020H and its screen refresh rate is 144Hz. When I use the Shrink function and drag the mouse to resize the window, the screen flicker will happen in the shrinking window.

**Comment by gileli121** [comment]
Hi, please make sure that you enabled the following option:
![image](https://user-images.githubusercontent.com/17680514/96331786-d3251c80-1068-11eb-8e58-7fdaa05314ea.png)

When it is enabled, it should not happen

**Comment by gileli121** [comment]
This issue should not happen in v5 because the implementation for shrink in free mode is different
You can download v5 from here https://github.com/gileli121/WindowTop/releases/tag/v5.x.x
Closed
