### ISSUE TITLE
Please provide both dark mode pro and not pro at the same time

### ISSUE THREAD

**Issue by luo-chuan** [gileli121/WindowTop#47]
Sometime, user need the dark mode (not pro), but sometime user need the dark mode pro. So, please provide both two options  at the same time.

**Comment by gileli121** [comment]
Thanks, I also thought about it.
Thanks for you feedback.
I will develop the option when I get to it.

**Comment by gileli121** [comment]
@luo-chuan 
Implemented in v5 (for now only beta version - https://github.com/gileli121/WindowTop/releases/tag/v5.x.x )
