### ISSUE TITLE
Respond abnormally slowly when changing settings

### ISSUE THREAD

**Issue by ToffeeNeko** [gileli121/WindowTop#50]
Hi I read through "Important Known Issues" and found it not including anther problem mentioned yesterday in #49.

When trying to change WindowTop settings by right clicking the taskbar icon and selecting an option, it always takes more than 5 seconds to respond to the action. 

For example, I want change the hot key for shrinking a window, after clicking on 
![image](https://user-images.githubusercontent.com/53738915/96392653-68680400-1182-11eb-8c6a-087c6c9705d7.png),
it take several seconds before this window
![image](https://user-images.githubusercontent.com/53738915/96392763-ae24cc80-1182-11eb-9c68-fe30c44149a5.png) 
coming out.

**Comment by gileli121** [comment]
Hello, please try this version:
[WindowTop Portable - test issue 50.zip](https://github.com/gileli121/WindowTop/files/5403349/WindowTop.Portable.-.test.issue.50.zip)

Let me know if it respond fast.
Please also compare CPU usage between this version and the regular version.
Try to use it 1-2 days.

If it is stable, let me know

**Comment by gileli121** [comment]
Test also this version.
I think that this one should be more stable - 
[WindowTop Portable - test issue 50 - option 2.zip](https://github.com/gileli121/WindowTop/files/5403409/WindowTop.Portable.-.test.issue.50.-.option.2.zip)

**Comment by ToffeeNeko** [comment]
Good news! The first version doesn't work, while the second one works perfectly. In both version the respond speed is much faster than before. As for CPU usage, I think it's similar to the older version. However since I don't have a professional tool to test it, this result may not be convincing.

**Comment by gileli121** [comment]
OK thanks, I will also check it. Please continue to use it and update here if it is stable.
I am not sure that it is fully stable.
I will also use it myself for a while before I will release it to production

**Comment by ToffeeNeko** [comment]
OK. Oh by accident I found 'enable click through' feature doesn't work with some win10 apps, such as mail, photos, weather...etc.

**Comment by ToffeeNeko** [comment]
And all features don't work with system apps like taskmgr and regedit

**Comment by ToffeeNeko** [comment]
> OK. Oh by accident I found 'enable click through' feature doesn't work with some win10 apps, such as mail, photos, weather...etc.

After testing this happens on all UWP apps.

**Comment by gileli121** [comment]
Hi, I know that it will not work on UWP apps.
I think that I disabled the option to enable click through in the old toolbar and forgot to do it in the new modern toolbar

**Comment by ToffeeNeko** [comment]
Gotcha :)

**Comment by gileli121** [comment]
@ToffeeNeko 
Can you try version 5 beta and confirm that it fixed? 
Download from here:
https://github.com/gileli121/WindowTop/releases/tag/v5.x.x

**Comment by ToffeeNeko** [comment]
Thanks for the reminder! Delaying problems now are no longer existing in new version, however... 

Under 3840*2160 resolution, the shrunken windows will 'disappear' (Actually they go out of the bottom right side) from desktop instead of shrink to the center, no matter what the system scaling is (250% or 100% etc.).  

What's more, there's another problem happening to the preview buttons in settings:
![image](https://user-images.githubusercontent.com/53738915/111667646-ef2d1580-87e2-11eb-81ca-085f31efcbcc.png)
I think it's same with problem in #49

**Comment by gileli121** [comment]
@ToffeeNeko 
Can you check it again? #49 is fixed now.
About the issue that window disappeared, in v5.2.x I worked very hard to make sure that it will never happen.
I fixed multiple scenarios when windows disappeared..

I will ask you to test again when v5.2.x will be released
