### ISSUE TITLE
Shrink Pro - Add option to control window while window is shrunken

### ISSUE THREAD

**Issue by gileli121** [gileli121/WindowTop#54]
Instead of implementing #28 we will implement an option to pass through the mouse events to the shrunken window and this way you get full control of the window even if it is shrunken.
So in use-case that the user wants to change the volume of playing video inside shrunken window, the user will able to do it because he has full control on the shrunken window (For example, the user will able to access the volume control of YouTube video player inside the shrunken window)

An investigation has been done and it is doable

**Comment by cyberluke** [comment]
Sounds exactly like what I need...

**Comment by gileli121** [comment]
@cyberluke 

First preview:
https://www.youtube.com/watch?v=s-X25RaGpVM
Note that it will show this option by default only for Google Chrome, Firefox and Chromium Edge.

I am not Microsoft so this stuff require me some "hacking".
I can't make work for every program as I liked even if I am very experienced with Win32 API.

It is hard but I think that it is pretty good to get it working perfectly with Google Chrome and Chromium Edge
See the video

**Comment by gileli121** [comment]
New video after more day of work on this feature:
https://www.youtube.com/watch?v=lph5___lCaw

**Comment by cyberluke** [comment]
Perfect! Looks very nice! Now it leans towards smart window management.

**Comment by gileli121** [comment]
I was able to hack it more.
A lot of thanks to https://devblogs.microsoft.com/oldnewthing/20101230-00/?p=11873
I really wrote low-level code that does what Windows operating system does when it processing mouse inputs

Now it should work with much more programs and not only Chrome, Firefox and Edge.

**Comment by gileli121** [comment]
Implemented in v5.2.0 (Not released yet)

**Comment by gileli121** [comment]
It did not passed QA 
Multiple issues found when using different DPI configurations 
I fixed most of them yesterday but there is still work here

**Comment by gileli121** [comment]
After I reimplemented the logic and made more fixes, this is how it will work on different monitor DPI configurations

| Screen 1 DPI | Screen 2 DPI | Working fine?                                            |
|--------------|--------------|----------------------------------------------------------|
| 100%         | 100%         | *Yes                                                     |
| 100%         | 125%         | No - The mouse is not positioned correctly on the window |
| 100%         | 150%         | No - The mouse is not positioned correctly on the window |
| 125%         | 100%         | *Yes                                                     |
| 150%         | 100%         | *Yes                                                     |
| 125%         | 125%         | *Yes                                                     |
| 125%         | 150%         | *Yes                                                     |

About **Yes**
It will work pereft for:
Google Chrome, Firefox, Edge and maybe more browsers.
But for some windows the mouse may not work when shrink enabled or the mouse may positioned incorrectly 

I tried the best to solve all of these issues but can't get perfect results for any window.

It will be released in the next version

**Comment by gileli121** [comment]
@cyberluke 
I released the very first version with this function here:
https://github.com/gileli121/WindowTop/discussions/83

Please let me know how it works and comment there what you think
