### ISSUE TITLE
Smart Transparency Glass mode not working on OneNote 2016 (office 365)

### ISSUE THREAD

**Issue by jakkaas** [gileli121/WindowTop#57]
When i click smart transparency this happens.

![image](https://user-images.githubusercontent.com/43289832/107403615-57754100-6b2b-11eb-9bdb-9f08ccbcb520.png)

But when i start writing on it, the window changes to non transparent.

![image](https://user-images.githubusercontent.com/43289832/107403714-75db3c80-6b2b-11eb-9c51-c36b994f2290.png)

**Comment by gileli121** [comment]
Hello,
I am working on new version that I rewriting in C#.
I also rewrote the smart transparency algorithm and it should render now much more better (You can see it in action in http://glass-code.com/ )

The next version should be much more modern and with big improvements, and maybe the issue you have is already fixed in the new version.

I will send you today alpha version of the next big version, and let me know if you still get this issue.
I will post here later another message with the new version that you can try.

**Comment by jakkaas** [comment]
Thank you. I will try and let you know

**Comment by gileli121** [comment]
Hello, can you please try this build:
[Build.zip](https://github.com/gileli121/WindowTop/files/5966855/Build.zip)


Run this file 
![image](https://user-images.githubusercontent.com/17680514/107666639-65e06b80-6c97-11eb-8db0-c40f1e588271.png)

Note that this is a rewritten version in C# and it is far from be ready.
But the Glass effect may work (even if not fully tested yet).

This version is far from being ready. It does not even have an icon.
I only want to know how the Glass effect is working for you on this app so I will know if I should keep this bug open or not.

Thanks

**Comment by jakkaas** [comment]
Hello
While trying Glass mode, It is telling me various .dll are missing
![image](https://user-images.githubusercontent.com/43289832/107843308-22e5db80-6df0-11eb-9277-11a88acd976d.png)
![image](https://user-images.githubusercontent.com/43289832/107843310-237e7200-6df0-11eb-911c-9458fe0c44ec.png)
![image](https://user-images.githubusercontent.com/43289832/107843314-2d07da00-6df0-11eb-98ea-a8eb04750563.png)
![image](https://user-images.githubusercontent.com/43289832/107843315-2ed19d80-6df0-11eb-8ee5-be5454c39b7d.png)
![image](https://user-images.githubusercontent.com/43289832/107843329-44df5e00-6df0-11eb-8584-7e7680ac4b66.png)

**Comment by gileli121** [comment]
Hi, I see. There is a build issue and it is not tested yet.
I decided to wait with this version more until I have the first ready version.
So please wait.

It should take more than 3 weeks until I may have something ready.

**Comment by gileli121** [comment]
@jakkaas 
Can you try again with beta version 5?
Download from here:
https://github.com/gileli121/WindowTop/releases/tag/v5.x.x

**Comment by gileli121** [comment]
User did not responded.
I checked myself.
It worked
![image](https://user-images.githubusercontent.com/17680514/115345309-4a25a400-a1b7-11eb-9653-0bc458fa2f1a.png)


But there is issue with 4k and the fix depends on something I requested Microsoft 
In 4k it works slow.. known issue #19 

Closing this issue
