### ISSUE TITLE
Can not assign hotkeys. Exception.

### ISSUE THREAD

**Issue by tolgaulas** [gileli121/WindowTop#6]
I have the below problem when i like to assign shortcut; the dialog-box appears when i click ctrl or alt (and the program closes)

![image](https://user-images.githubusercontent.com/1431106/73129889-c9e9b080-3ffe-11ea-958d-196e4fb3900d.png)

**Comment by gileli121** [comment]
@tolgaulas 
I can't reproduce the issue.

Can you please provide the exact steps in to following format:
1. Step A
2. Step B
3. ...

**Expected Result**
Your expected result

**Actual Result**
The actual result

Thanks

**Comment by gileli121** [comment]
Fixed in v3.3.10
