### ISSUE TITLE
Problem: Can I set default Window Opacity rate globally?

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#61]
In this version I can just set the configuration for Windows, and it may set back to 75% when a new Window opened.
Can I save a global default configuration?

**Comment by WZ-Tong** [comment]
Note: I am a Pro user

**Comment by gileli121** [comment]
You want default configuration so that for example if you enabled opacity it will set to 90% for example (in case you defined 90% as default) right?

This is good idea. 
I think that I will add it

**Comment by WZ-Tong** [comment]
Yes, in that case I can just use hotkey to control all features (and maybe the rate can be set by hotkey).
Thanks

**Comment by WZ-Tong** [comment]
Have this developed yet?

Now I have the need to set 50％ opacity for all the window if I use the hotkey.

Sorry but when I rememberd this issue, I found it was closed by myself

**Comment by gileli121** [comment]
Planed for v5.3.x

**Comment by gileli121** [comment]
Implemented
![image](https://user-images.githubusercontent.com/17680514/116451059-b57d0f00-a864-11eb-9d54-59750b251e9c.png)

@WZ-Tong 
Please test it in version:
[WindowTop 5.2.8 - Beta - Portable.zip](https://github.com/gileli121/WindowTop/files/6393846/WindowTop.5.2.8.-.Beta.-.Portable.zip)
[WindowTop 5.2.8-beta - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6393849/WindowTop.5.2.8-beta.-.setup.exe.zip)

Let me know how it works :)

**Comment by WZ-Tong** [comment]
Seems right, wait for release

**Comment by gileli121** [comment]
Great!
Thanks,
Please have a look on #84 
Soon I will release beta version also for #84
