### ISSUE TITLE
Bug: When setting hotkey to "Smart transparency" it appeares

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#62]
![QQ截图20210320141856](https://user-images.githubusercontent.com/77199564/111861216-892dc300-8987-11eb-9fa8-249d01974211.png)

**Comment by gileli121** [comment]
Hi, please try version
https://github.com/gileli121/WindowTop/releases/tag/v5.x.x
Let me know if it fixed for you

**Comment by WZ-Tong** [comment]
![Uploading QQ截图20210321143609.png…]()

**Comment by WZ-Tong** [comment]
![QQ截图20210321143609](https://user-images.githubusercontent.com/77199564/111896264-46d1b800-8a53-11eb-9e7b-2c903871ae1d.png)

**Comment by gileli121** [comment]
Seems like it is build issue.
I will fix it now on next beta release and update you soon

**Comment by gileli121** [comment]
@WZ-Tong 
Please download v5.1.2 and let me know if it fixed for you

**Comment by WZ-Tong** [comment]
Alright it is fixed
