### ISSUE TITLE
Problem: Hotkey when work

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#64]
It's possible when you need to switch CLICK-THROUGH mode on and off independently like v4, but the feature seems like to be deleted in v5.

When I enable CLICK-THROUGH and disable it, the window should be set back to its previous state rather than remains "Top" and "Opacity"

**Comment by WZ-Tong** [comment]
In that case, I must: Turn off CLICK-THROUGH, Turn off opacity, Turn off Set on Top to make my Window normal

**Comment by gileli121** [comment]
Thanks for the report.
I will fix it soon and update you later

**Comment by gileli121** [comment]
@WZ-Tong
Please download v5.1.2 and let me know if it fixed for you

**Comment by WZ-Tong** [comment]
It's right now
