### ISSUE TITLE
Problems after enable and disable CLICK-THOUGH mode in v5

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#66]
After enable and disable CLICK-THOUGH mode in v5, my "auto hide" taskbar can't show up

**Comment by WZ-Tong** [comment]
and what I want is a hotkey just enable and disable CLICK-THROUGH mode and doesn't affect other options like v4

**Comment by gileli121** [comment]
I confused.
In #64 
You told that when you disable the CLICK-THROUGH mode via hot-key, you expected that it will disable also the opacity.

Here you said you want this:
> and what I want is a hotkey just enable and disable CLICK-THROUGH mode and doesn't affect other options like v4


But this is how it was before I fixed #64 

So please explain better what you want.

**Comment by WZ-Tong** [comment]
For example, I set a window to be opacity, then I enable the click-through mode to do something, then I want to disable click-through mode while keep the window opacity. (all operated by hotkeys)

In the v4, I can do it with 2 hotkeys: set-opacity, set-click-through, but in v5 I must use 3 hotkeys: set-opacity, ENABLE-click-through, DISABLE-click-through

Sorry but my first language is not English so it made you confused

**Comment by gileli121** [comment]
Sorry, I did not understand what you expect. 
Please describe it in this format, example:

**Steps I do**
1. Set window on top without hotkey
2. Enable the click-through with hotkey
3. Disable click-through

**I Expect:**
* The window should be set on top
* click-through mode should be disabled

**Comment by gileli121** [comment]
I checked how it worked in v4.
In v4, if you disabled the click-through option, the opacity will still stays. 
But this is exactly how it was before I fixed #64 
So I am going to revert the fix.

Feel free to reopen #64 but please explain what you want.
Maybe you want hotkey to restore window to it's original state?
If so, please write it in #64

**Comment by WZ-Tong** [comment]
Right, I just wanted hotkey to restore window to it's original state, thanks.

**Comment by ryrane** [comment]
hi can you disable the opacity in click through mode? everytime i enable click through mode the opacity changes, is it possible to maintain the 100% opacity in click through mode?
