### ISSUE TITLE
Shrink window, other issues and few suggestion in Version 5.1.3 Beta

### ISSUE THREAD

**Issue by jakkaas** [gileli121/WindowTop#68]
1) Shrink window is not scaling properly
![image](https://user-images.githubusercontent.com/43289832/112095050-d006fd00-8bc1-11eb-90dd-64c15a1c8cc4.png)
I tried all the option but still unable to scale properly 

2) I cannot click on shrink window to unshrink it. I have to unshrink it from toolbar and thus need to keep the toolbar on.
3) Option to use dark mode with shrink window should also be available.
4) Option to use transparent mode with dark mode.
5) Every time I use glass mode for same window it reset to its original setting. Option to keep the changed setting of  glass mode with every window i used.
6) Glass mode should be considered as advance transparent mode and click through option and its key should also work with glass mode
 Also glass mode is working fine with OneNote but it is not yet as good and clear as it was with autoIt.
 
 Thanks

**Comment by gileli121** [comment]
@jakkaas 

Thanks for the report!
You reported about a lot of things.

I will refer only to `1.` for now.


**Can you restart the computer and try again?**
It may be fixed after restart

**What is your operating system? It should be Windows 10**

**For each screen, fill this information:**
- Resolution
- DPI scaling

**Comment by gileli121** [comment]
Hello,
I was able to reproduce the issue by changing the scaling to 125% on first monitor.
I will work on fix now.

Good bug

**Comment by gileli121** [comment]
@jakkaas 
This issue
![image](https://user-images.githubusercontent.com/17680514/112150653-01df8a00-8be9-11eb-8052-0ca4b4125410.png)

Fixed now in v5.1.4
Please download it and let me know if it fixed for you

**Comment by jakkaas** [comment]
Yes both issue 1 and 2 are fixed

**Comment by gileli121** [comment]
Great, closed
