### ISSUE TITLE
Feature request: Hotkey of opening the toolbar

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#75]
Support opening the toolbar using hotkey. So that I can disable the toolbar while editing the setting in some cases

**Comment by gileli121** [comment]
@WZ-Tong 
Thanks, Easy to develop.
I will do it later after I will finish with implementing 
https://github.com/gileli121/WindowTop/issues/54
And after I finish to fix few issues in the dark-mode and glass modes

**Comment by gileli121** [comment]
Implemented in v5.2.0 (Not released yet)

**Comment by gileli121** [comment]
@WZ-Tong 
Released
![image](https://user-images.githubusercontent.com/17680514/114294275-1efbd000-9aa6-11eb-98ea-1deacb5f5212.png)

Download it in the download section :)

**Comment by WZ-Tong** [comment]
Thanks, that's help.
But what's the "temporary" means?

**Comment by gileli121** [comment]
It means that it will not save it to the settings.
If you disabled the toolbar menu via hotkey, it will be disabled until you restart the program.
If you do the same from the settings window, the change will be saved so also after restart you will not have toolbar
