### ISSUE TITLE
Feature Request: Customable preview size for shrink window

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#76]
When the mouse is pointing the shrink window, there is a preview, but the size is not customable, please add MAYBE the selection:
1. preview in a fixed size
2. preview in a fixed rate (percent, 100% for original size preview)
3. preview in full screen (maybe with opacity)

**Comment by gileli121** [comment]
Planed for v5.3.x

**Comment by gileli121** [comment]
Screenshots:
![image](https://user-images.githubusercontent.com/17680514/116779657-3d8b3080-aa80-11eb-9c5a-39d44086b30d.png)
![image](https://user-images.githubusercontent.com/17680514/116779678-61e70d00-aa80-11eb-92e5-2ba300742eed.png)

**Comment by gileli121** [comment]
Implemented option to configure the default size of the shirnk box
![image](https://user-images.githubusercontent.com/17680514/116781927-cf019f00-aa8e-11eb-8e54-fba12408de01.png)

**Comment by WZ-Tong** [comment]
Right! Thanks

**Comment by gileli121** [comment]
Implement option to configure the maximum size of the shrink box for showing the bigger mouse hover preview
![image](https://user-images.githubusercontent.com/17680514/116783306-b0070b00-aa96-11eb-8358-8bd1b00f8a7a.png)

**Comment by gileli121** [comment]
@WZ-Tong 
Please let me know how it works for you:
[WindowTop 5.2.11-beta - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6409586/WindowTop.5.2.11-beta.-.setup.exe.zip)
[WindowTop 5.2.11 - Beta - Portable.zip](https://github.com/gileli121/WindowTop/files/6409587/WindowTop.5.2.11.-.Beta.-.Portable.zip)

**Comment by gileli121** [comment]
@WZ-Tong 
Please try this build:
[WindowTop 5.2.12-beta - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6409681/WindowTop.5.2.12-beta.-.setup.exe.zip)
[WindowTop 5.2.12 - Beta - Portable.zip](https://github.com/gileli121/WindowTop/files/6409682/WindowTop.5.2.12.-.Beta.-.Portable.zip)

I fixed some bug

**Comment by gileli121** [comment]
Video:
https://www.youtube.com/watch?v=5eBofGSdenU

**Comment by gileli121** [comment]
@WZ-Tong 
Please test v5.2.13-Beta
I added more few fixes and there is also missing german translations for this feature that now included (but in your case you don't care because you Chinese but don't worry, now I will add also missing Chinese translations)

[WindowTop 5.2.13 - Beta - Portable.zip](https://github.com/gileli121/WindowTop/files/6410236/WindowTop.5.2.13.-.Beta.-.Portable.zip)
[WindowTop 5.2.13-beta - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6410237/WindowTop.5.2.13-beta.-.setup.exe.zip)

**Comment by gileli121** [comment]
@WZ-Tong 
Any updates? It looks stable?

**Comment by WZ-Tong** [comment]
Seems stable

**Comment by gileli121** [comment]
Great, thank you
