### ISSUE TITLE
Problem / Feature Request: the position of the unshrink window

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#77]
Add **"an option"** that when I unshrink a window, the position will follow the current move.

For examples:
In case that I have **two** monitors, shrink Window A in the **first** monitor, move the shrink-ed window to the **second** monitor, unshrink it. In the current version the window will appear in the first monitor, while I think in this case the window should follow the move and appears in the second window.

Same reason when I shrink a window in the left side, drag it to the right side, then unshrink it. The window should appeared in the right side, following the move

P.S. Maybe this feature should appear as an option that everyone (or PRO) can choose.

**Comment by gileli121** [comment]
Thanks for the suggestion.
This is not anything like paid feature.
It sounds like a correct default behavior.
I will tag this issue as bug and improvement

**Comment by gileli121** [comment]
Implemented in v5.2.0 (Not released yet)

**Comment by gileli121** [comment]
@WZ-Tong, Released

Please download v5.2.0 from the download page

Let me know if it works better now :)

**Comment by WZ-Tong** [comment]
Right! Just what I need!
