### ISSUE TITLE
Change the save directory of the configuration file

### ISSUE THREAD

**Issue by Vstory** [gileli121/WindowTop#79]
The currently installed version of WindowTop configuration file, saved in `C:\Users\xxx\AppData\Roaming\WindowTop` .
I customized the installation location during installation. Can the configuration file be saved in the customized installation location?

**Comment by gileli121** [comment]
You can use portable version instead. In portable mode the configuration is where the WindowTop.exe is

**Comment by Vstory** [comment]
> You can use portable version instead. In portable mode the configuration is where the WindowTop.exe is

Thanks, I get it.
