### ISSUE TITLE
The difference between the portable version and the installation version

### ISSUE THREAD

**Issue by Vstory** [gileli121/WindowTop#80]
Is the difference between the portable version and the installed version only the boot from the boot?
I can modify the registry to solve the problem.
Are there other differences?

**Comment by gileli121** [comment]
This is the only difference. In portable mode it will not allow you to start it with Windows from the settings page.
But you can do some hack as you describe to solve it if you really want

**Comment by Vstory** [comment]
> This is the only difference. In portable mode it will not allow you to start it with Windows from the settings page.
> But you can do some hack as you describe to solve it if you really want

Thanks, I get it.
