### ISSUE TITLE
Idea: Customizable notification

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#84]
Log:
Changes
Removed notification when enabling/disabling set-top via hotkey

Maybe the visibility of all the notifications can be set by user?

**Comment by gileli121** [comment]
Screenshots:
![image](https://user-images.githubusercontent.com/17680514/116727680-8b0a8d80-a9ed-11eb-8385-a32d9eddccb6.png)
![image](https://user-images.githubusercontent.com/17680514/116727743-a37aa800-a9ed-11eb-81c9-b7eaaabd4a6d.png)

**Comment by gileli121** [comment]
@WZ-Tong 
Please let me know how this feature works in this version:

[WindowTop 5.2.9 - Beta - Portable.zip](https://github.com/gileli121/WindowTop/files/6407129/WindowTop.5.2.9.-.Beta.-.Portable.zip)
[WindowTop 5.2.9-beta - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6407130/WindowTop.5.2.9-beta.-.setup.exe.zip)

**Comment by WZ-Tong** [comment]
Seems right, I'll report if there is any bugs until this issue close

**Comment by gileli121** [comment]
@WZ-Tong 
Any updates? Do you think that it is stable?

**Comment by WZ-Tong** [comment]
Seems right, maybe this part can be released

**Comment by gileli121** [comment]
Thanks!
