### ISSUE TITLE
WindowTop fails to enable dark-mode when it start by Windows

### ISSUE THREAD

**Issue by Beurling** [gileli121/WindowTop#86]
sadlly dark mode in this app doesn't work.

**Comment by gileli121** [comment]
@Beurling 
Hello, can you try please to open winver:
![image](https://user-images.githubusercontent.com/17680514/114713298-a90f9700-9d39-11eb-846b-e6318104dcfa.png)

And let me know what the tool shows you?
In my case it showing:
![image](https://user-images.githubusercontent.com/17680514/114713392-bf1d5780-9d39-11eb-8f5b-c7b9f8e489f0.png)


If you have before **20H1**, dark mode will not work.
You should update your Windows 10 to the last version

**Comment by Beurling** [comment]
thanks for you reply.I just checked that I am using the newest system.

![Snipaste_2021-04-14_21-13-11](https://user-images.githubusercontent.com/48503044/114716088-4bde0a80-9d66-11eb-9e1e-92d2242cd163.png)

**Comment by gileli121** [comment]
Can you tell me what error you see when you enable dark mode?
Can you send screenshot?

**Comment by gileli121** [comment]
Hello, please download the following build:
[WindowTop - Support Build.zip](https://github.com/gileli121/WindowTop/files/6315724/WindowTop.-.Support.Build.zip)

This build comes with functionality to write to log file and to dump any fatal errors (Exceptions).


Do the following steps:

1. Make sure you exited WindowTop
2. Extract this ZIP 
3. Run WindowTop.exe 
![image](https://user-images.githubusercontent.com/17680514/114826884-b592fe80-9dd0-11eb-970c-4c9de5d1ec5f.png)
4. Try to reproduce this issue
5. After you reproduced the issue, exit WindowTop
6. Send me this file
![image](https://user-images.githubusercontent.com/17680514/114827027-db200800-9dd0-11eb-8a71-2689bb51606e.png)


I will review this log and hope to find out what goes wrong there.

**Comment by gileli121** [comment]
@Beurling 

Hello again,
I was able to reproduce the user problem.

To reproduce the problem, you need that WindowTop will start with windows.
Then, dark mode will fail.

The new version also failing but this time it shows a better error and it will not crash like v5.2.1
![image](https://user-images.githubusercontent.com/17680514/115108080-3986eb00-9f77-11eb-8b75-5fe411709cc4.png)

Now, the workaround is to exit WindowTop and start it again manually.
If you start WindowTop manually It will work
This is the key point here.. To reproduce the problem, the program should start by Windows first and not by the user itself.. then the program fails to activate dark mode

Currently the only workaround is as I said, to exit WindowTop and start it again.

I will work on a fix now

Thanks for the report!

**Comment by gileli121** [comment]
Fixed in v5.2.4

### v5.2.4
* Fixed: Toolbar - Fixed bug that after disabling the interactive mode via the toolbar, the button still shows as selected
* Fixed: Bug that when the program starts by windows, dark-mode and glass-mode fail to work (#86)
* Fixed: Shrink feature - Fixed bug that the bigger preview not showing on the small shrink-box when DPI is high
* Fixed: Shrink feature - Fixed bug that the bigger preview was showing also when the shrink-box was a little big
