### ISSUE TITLE
Windowtop moves Small popup windows to center of screen

### ISSUE THREAD

**Issue by demdante** [gileli121/WindowTop#95]
I have noticed an odd issue where Windowtop will inexplicably move certain small popup windows to the center of the screen.  Since you are familiar with the scripting language autoit (I use autoit a lot too), an example of one such window is the small little window with a progress bar that appears when you compile a script in Scite for autoit.  This is what happens when Windowtop is not running (eg how the window behaves normally):

![firstcompile](https://user-images.githubusercontent.com/64720591/118373673-9b9f3400-b5a7-11eb-8a4a-cb9170e5468b.gif)

While this is what happens when Windowtop is running:

![seccompile](https://user-images.githubusercontent.com/64720591/118373721-c5585b00-b5a7-11eb-9e5c-d4d87c761bba.gif)

Another window that exhibits this behavior is the little popup window that displays a new message in Microsoft teams.  Here is what it normally does (withwintop not running):

![firstteams](https://user-images.githubusercontent.com/64720591/118375831-d6a76480-b5b3-11eb-85eb-f96c8c335180.gif)

And here is what it does when windowtop is running:

![secteams](https://user-images.githubusercontent.com/64720591/118375845-e3c45380-b5b3-11eb-845f-eb5381646b30.gif)

Let me know if you need more info!

**Comment by gileli121** [comment]
Thanks for the report.
I will check it when I get to it

**Comment by gileli121** [comment]
May be the same as #98

**Comment by gileli121** [comment]
I was able to reproduce the issue

**Comment by gileli121** [comment]
@demdante 
Please try this version and let me know if it is stable and if the problem fixed:
[WindowTop 5.3.1 - setup.zip](https://github.com/gileli121/WindowTop/files/6562528/WindowTop.5.3.1.-.setup.zip)

**Comment by demdante** [comment]
Awesome!!  I have confirmed the issue is no longer present.  Thank you!!!
