### ISSUE TITLE
Incompatible with some program(not function wise)

### ISSUE THREAD

**Issue by WilliamZY** [gileli121/WindowTop#98]
I discovered that when WindowTop is running, no matter a program is in the blacklist/whitelist, it will still cause issue for other programs.
I find that when WindowTop and [Eagle](https://eagle.cool/download/) are running together, there will be a extra, non-interactive window from Eagle showed up. Changing order to start the software/add eagle to blacklist/remove eagle from white list also doesn't resolve the problem. 

When WindowTop is not running, everything is fine, no extra window. 
Eagle and WindowTop both running
![image](https://user-images.githubusercontent.com/12370751/119267302-4c08da00-bc31-11eb-809f-b66f33f310d7.png)
Eagle only
![image](https://user-images.githubusercontent.com/12370751/119267339-870b0d80-bc31-11eb-9ecd-4266afe01d62.png)
Setting of the WindowTop
![image](https://user-images.githubusercontent.com/12370751/119267390-b0c43480-bc31-11eb-96f5-d6e76c1d396d.png)
The Problem Window:
![image](https://user-images.githubusercontent.com/12370751/119267526-655e5600-bc32-11eb-94b3-51be1c19593c.png)

I have also post a short video on [youtube](https://youtu.be/K3ZwV7_rRXI) to demostrate the problem.

**Comment by gileli121** [comment]
Thanks for the report.
I know what may cause this issue.
I will work on fix in the next week

**Comment by gileli121** [comment]
@WilliamZY 
I could not reproduce the issue but I suspect that this code causing the problem:
![image](https://user-images.githubusercontent.com/17680514/119609853-eff4b000-be00-11eb-9875-d91c3ea701e2.png)

Please try this file
[WindowTop.zip](https://github.com/gileli121/WindowTop/files/6544141/WindowTop.zip)

Extract the zip and replace the WindowTop.exe file in the installation folder with WindowTop.exe in the zip.
This build does not contain this code.. but it is not yet final solution.. I just need to see if it this was the cause

**Comment by WilliamZY** [comment]
Just tried that one, but the problem still remains.

**Comment by gileli121** [comment]
@WilliamZY 
Just saw a simillar report with different program
https://github.com/gileli121/WindowTop/issues/95
I am hopping that by reproducing and solving #95 I will solve this issue ( #98 )

**Comment by gileli121** [comment]
@WilliamZY 
Please try this version and let me know if it is stable and if the problem fixed:
[WindowTop 5.3.1 - setup.zip](https://github.com/gileli121/WindowTop/files/6562528/WindowTop.5.3.1.-.setup.zip)

**Comment by WilliamZY** [comment]
Unfortunately, it doesn't help with the problem.

**Comment by gileli121** [comment]
So it is not the same as #95 for sure.
I will check the files you sent me and will try to reproduce it using your files

**Comment by gileli121** [comment]
@WilliamZY 
I was able to reproduce the issue using the settings files of Eagle + Settings files of WindowToo
that you sent me.

Indeed, the fix for #95 did not fix this issue.

**Comment by gileli121** [comment]
@WilliamZY 
I fixed it. 
Seems that the program "Eagle" creating an extra window and hides it unusually by setting the opacity level 0.

Please try this version (another v5.3.1)
[WindowTop 5.3.1 - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6565579/WindowTop.5.3.1.-.setup.exe.zip)

Let me know if it fixed for you

**Comment by WilliamZY** [comment]
Yes, the latest 5.3.1 fixed the problem.
Well Done.

**Comment by WilliamZY** [comment]
@gileli121 
And I believe that the latest 5.3.1 is still not the final release right? As now the WindowTop leaves a blank black window, and if I close the window the program exits. 

If that is just a debugging feature, then the issue can be closed.

**Comment by gileli121** [comment]
@WilliamZY 
It could be the final v5.3.1 version but then you reported about this problem.
Yes, it is a debugging feature that I was supposed to disable.

I will release now final v5.3.1 version

**Comment by gileli121** [comment]
@WilliamZY 
Please download it again from
https://github.com/gileli121/WindowTop/releases/tag/v5.x.x
